#!/bin/bash

# Setup Automated MySQL Backup Cron Jobs
# Usage: ./setup_cron.sh

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Logging function
log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1"
}

log "Setting up automated MySQL backup cron jobs..."

# Create cron job entries
CRON_ENTRIES="
# MySQL Backup Jobs - Auto-generated by setup_cron.sh
# Full backup daily at 2:00 AM
0 2 * * * $SCRIPT_DIR/backup_full.sh >> /var/log/mysql_backup_cron.log 2>&1

# Binary log management weekly on Sunday at 3:00 AM
0 3 * * 0 $SCRIPT_DIR/manage_binlogs.sh purge 7 >> /var/log/mysql_backup_cron.log 2>&1

# Backup verification daily at 4:00 AM
0 4 * * * $SCRIPT_DIR/verify_backup.sh >> /var/log/mysql_backup_cron.log 2>&1
"

# Backup existing crontab
log "Backing up existing crontab..."
crontab -l > /tmp/crontab_backup_$(date +%Y%m%d_%H%M%S) 2>/dev/null || true

# Remove existing MySQL backup entries
log "Removing existing MySQL backup cron entries..."
(crontab -l 2>/dev/null | grep -v "MySQL Backup Jobs" | grep -v "$SCRIPT_DIR") | crontab - 2>/dev/null || true

# Add new cron entries
log "Adding new MySQL backup cron entries..."
(crontab -l 2>/dev/null; echo "$CRON_ENTRIES") | crontab -

# Verify cron installation
log "Verifying cron job installation..."
crontab -l | grep -A 10 "MySQL Backup Jobs"

# Create log file with proper permissions
sudo touch /var/log/mysql_backup_cron.log
sudo chmod 644 /var/log/mysql_backup_cron.log

log "Cron jobs setup completed successfully!"
log ""
log "Scheduled jobs:"
log "  - Full backup: Daily at 2:00 AM"
log "  - Binary log cleanup: Weekly on Sunday at 3:00 AM"
log "  - Backup verification: Daily at 4:00 AM"
log ""
log "Log file: /var/log/mysql_backup_cron.log"
log ""
log "To modify schedule, edit crontab manually:"
log "  crontab -e"